import type { Metadata } from "next";
import { roboto } from "../styles/fonts";
import CssBaseline from "@mui/material/CssBaseline";
import { Navbar, Footer } from "@/components/common";
import "@/styles/globals.css";

export const metadata: Metadata = {
  title: "Vinyl Vault",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <CssBaseline>
          <Navbar />
          <div>{children}</div>
          <Footer />
        </CssBaseline>
      </body>
    </html>
  );
}
