import type { Metadata } from "next";
import Provider from "@/redux/provider";
import { Navbar, Footer } from "@/components/common";
import { roboto } from "../styles/fonts";
import "@/styles/globals.css";
import { Setup, ThemeRegistry } from "@/components/utils";

export const metadata: Metadata = {
  title: "Vinyl Vault",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <ThemeRegistry>
          <Provider>
            <Setup />
            <Navbar />
            <div>{children}</div>
            <Footer />
          </Provider>
        </ThemeRegistry>
      </body>
    </html>
  );
}
