# Generated by Django 4.2.7 on 2023-11-30 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault_api', '0008_remove_user_spotify_id_spotifyprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='artwork',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='album',
            name='release_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='musicians',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='order_num',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='user_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='favorite_genres',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
