# Generated by Django 4.2.7 on 2023-12-01 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault_api', '0009_alter_album_artwork_alter_album_release_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='id',
        ),
        migrations.AddField(
            model_name='album',
            name='album_id',
            field=models.BigAutoField(default=21, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
