# Generated by Django 4.2.7 on 2023-11-16 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault_api', '0003_rename_spotify_id_user_spotify_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='spotify_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
