# Generated by Django 4.2.7 on 2023-11-18 18:04

from django.db import migrations
import vault_api.models


class Migration(migrations.Migration):

    dependencies = [
        ('vault_api', '0006_alter_album_artwork_alter_album_release_date'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', vault_api.models.CustomUserManager()),
            ],
        ),
    ]
